// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNfrliRMx8lal-bX70AYz7t03mZ0tTBAk',
    appId: '1:71192441917:web:edc8d92ba35ebe8a316654',
    messagingSenderId: '71192441917',
    projectId: 'rd-alerta',
    authDomain: 'rd-alerta.firebaseapp.com',
    storageBucket: 'rd-alerta.firebasestorage.app',
    measurementId: 'G-62LT7HC2C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRxOsUCp2yJyXb7L1R123mMNTH1h2CA44',
    appId: '1:71192441917:android:6e67d717f3004d31316654',
    messagingSenderId: '71192441917',
    projectId: 'rd-alerta',
    storageBucket: 'rd-alerta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5cNks07uBkI0y3H8F5HdMVhEFPg3dNE4',
    appId: '1:71192441917:ios:b1727c20dff140f7316654',
    messagingSenderId: '71192441917',
    projectId: 'rd-alerta',
    storageBucket: 'rd-alerta.firebasestorage.app',
    iosClientId: '71192441917-ccc14elemh0g3sko4ld6ql4nts6tmitc.apps.googleusercontent.com',
    iosBundleId: 'com.example.rdAlerta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5cNks07uBkI0y3H8F5HdMVhEFPg3dNE4',
    appId: '1:71192441917:ios:b1727c20dff140f7316654',
    messagingSenderId: '71192441917',
    projectId: 'rd-alerta',
    storageBucket: 'rd-alerta.firebasestorage.app',
    iosClientId: '71192441917-ccc14elemh0g3sko4ld6ql4nts6tmitc.apps.googleusercontent.com',
    iosBundleId: 'com.example.rdAlerta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNfrliRMx8lal-bX70AYz7t03mZ0tTBAk',
    appId: '1:71192441917:web:c6c7aa24fe2d544e316654',
    messagingSenderId: '71192441917',
    projectId: 'rd-alerta',
    authDomain: 'rd-alerta.firebaseapp.com',
    storageBucket: 'rd-alerta.firebasestorage.app',
    measurementId: 'G-6F5P1EXH1R',
  );
}
